import type { NextConfig } from "next";

// Generated by Copilot
const nextConfig: NextConfig = {
  /* config options here */
  allowedDevOrigins: [
    // Allow ngrok domains
    "*.ngrok.io",
    "*.ngrok-free.app",
    "*.ngrok.app",
    // Add your specific ngrok domain if needed
    "a1c2-125-163-58-107.ngrok-free.app",
  ],
};

export default nextConfig;
